spring:
  datasource:
    initialization-mode: always

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

  data:
    rest:
      base-path: /api

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    logfile:
      enabled: true
  health:
    defaults:
      enabled: true

logging:
  level:
    root: info
  file:
    name: "log/1.txt"