server:
  port: 9001
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eureka-service:8001/eureka/
  server:
    eviction-interval-timer-in-ms: 15000
  instance:
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/library
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
management:
  endpoints:
    web:
      exposure:
        include: "*"