spring:
  application:
    name: configuration-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/okrasavina/config-repo
          search-paths: {application}

server:
  port: 5000
